SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

ALTER TABLE `yf_news`  ADD COLUMN `listorder` int(11) unsigned DEFAULT '50' AFTER `news_time`;
ALTER TABLE `yf_we_menu` ADD `we_menu_l` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'zh-cn' ;
ALTER TABLE `yf_plug_link` ADD `plug_link_l` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'zh-cn' ;
ALTER TABLE `yf_plug_ad` ADD `plug_ad_l` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'zh-cn' ;
ALTER TABLE `yf_options` DROP INDEX option_name;
ALTER TABLE `yf_options` ADD `option_l` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'zh-cn' ;
ALTER TABLE `yf_news` ADD `news_l` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'zh-cn' ;
ALTER TABLE `yf_menu` ADD `menu_l` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'zh-cn' ;
ALTER TABLE  `yf_admin` ADD  `member_id` INT( 6 ) UNSIGNED NOT NULL COMMENT  '对应会员ID';

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
